import StyledComponentsRegistry from "@/lib/registry";
import "./globals.css";
import { Overpass } from "next/font/google";
import { DefaultProviders } from "@/Providers/default-providers";
import Header from "@/components/Header";
import Footer from '@/components/Footer';

const overpass = Overpass({ weight: ["300", "600"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={overpass.className}>
        <StyledComponentsRegistry>
          <DefaultProviders>
            <Header />
            {children}
            <Footer />
          </DefaultProviders>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
