import StyledComponentsRegistry from "@/lib/registry";
import "./globals.css";

import { DefaultProviders } from "@/Providers/default-providers";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <DefaultProviders>
            {children}
            <Footer />
          </DefaultProviders>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
